/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eventremainder;

import static eventremainder.addPesertaEvent.getTabelModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import toSql.toSql;

/**
 *
 * @author Saputro
 */
public class addPesertaGroup extends javax.swing.JPanel {

    /**
     * Creates new form addPesertaGroup
     */
    public addPesertaGroup(toSql sql, String group) {
        initComponents();
        try {
            jTable1 = new javax.swing.JTable(getTabelModel(sql.getTable("select id,nama_wali,nama_murid,angkatan,no_induk from kontak where id not in (select k.id from kontak k inner join membergroup m on k.id=m.id_kontak where m.id_groups='"+group+"') order by angkatan,no_induk"))){
              private static final long serialVersionUID = 1L;
              public Class getColumnClass(int column) {
                    if(column==5)
                        return Boolean.class;
                    return Object.class;
                }
            };
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTable1);
        } catch (Exception ex) {
            Logger.getLogger(addPesertaEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt){
        if(jTable1.getSelectedColumn()!=jTable1.getColumnCount()-1){
            if((boolean)jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getColumnCount() - 1)){
                jTable1.setValueAt(false, jTable1.getSelectedRow(), jTable1.getColumnCount() - 1);
            } else {
                jTable1.setValueAt(true, jTable1.getSelectedRow(), jTable1.getColumnCount() - 1);
            }
        }
    }
    public static javax.swing.table.DefaultTableModel getTabelModel(ResultSet rs) throws Exception{
        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel();
        ResultSetMetaData metaData = rs.getMetaData();
        Object column[] = new String[metaData.getColumnCount()+1];
        for (int i = 0; i < column.length-1; i++) {
            column[i] = metaData.getColumnName(i + 1);
        }
        column[column.length-1]="Pilih";
        tableModel.setColumnIdentifiers(column);
        while (rs.next()) {
            Object data[] = new Object[column.length];
            for (int i = 0; i < column.length-1; i++) {
                data[i] = rs.getString(i + 1);
            }
            data[column.length-1] = false ;
            tableModel.addRow(data);
        }
        return tableModel;
    }
    public ArrayList<String> getPeserta(){
        ArrayList<String> data = new ArrayList<String>(); 
        for(int i=0;i<jTable1.getRowCount();i++)
            if((boolean)jTable1.getValueAt(i, jTable1.getColumnCount()-1))
                data.add((String)jTable1.getValueAt(i, 0));
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Pilih kontak untuk dimasukan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
