/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eventremainder;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import toSql.toSql;

/**
 *
 * @author Komando
 */
public class addPesertaEvent extends javax.swing.JPanel {

    /**
     * Creates new form addPesertaEvent
     */
    toSql sql;
    public addPesertaEvent(toSql s) {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        sql=s;
        refreshCombox();
        try {
            jTable1 = new javax.swing.JTable(getTabelModel(sql.getTable("select id,nama_wali,nama_murid,angkatan,no_induk from kontak"))){
              private static final long serialVersionUID = 1L;
              public Class getColumnClass(int column) {
                    if(column==5)
                        return Boolean.class;
                    return Object.class;
                }
            };
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTable1);
        } catch (Exception ex) {
            Logger.getLogger(addPesertaEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1.setEnabled(true);
        jRadioButton1ActionPerformed(null);
        jTable1.setEnabled(false);
    }
    private void refreshCombox(){
        try {
            String [] data = new String [0];
            ResultSet rs = sql.getTable("select * from groups");
            while(rs.next()){
                String dataX []= new String [data.length+1];
                for(int i=0;i<data.length;i++)
                    dataX[i]=data[i];
                dataX[data.length]=rs.getString("id")+" "+rs.getString("nama_group");
                data=dataX;
            }
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(data));
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static javax.swing.table.DefaultTableModel getTabelModel(ResultSet rs) throws Exception{
        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel();
        ResultSetMetaData metaData = rs.getMetaData();
        Object column[] = new String[metaData.getColumnCount()+1];
        for (int i = 0; i < column.length-1; i++) {
            column[i] = metaData.getColumnName(i + 1);
        }
        column[column.length-1]="Pilih";
        tableModel.setColumnIdentifiers(column);
        while (rs.next()) {
            Object data[] = new Object[column.length];
            for (int i = 0; i < column.length-1; i++) {
                data[i] = rs.getString(i + 1);
            }
            data[column.length-1] = false ;
            tableModel.addRow(data);
        }
        return tableModel;
    }
    public ArrayList<String> getPeserta(){
        ArrayList<String> data = new ArrayList<String>();
        if(jRadioButton1.isSelected()){
            try {
                String event[] = ((String)jComboBox1.getSelectedItem()).split(" ");
                ResultSet rs = sql.getTable("select id_kontak from memberGroup where id_groups="+event[0]+"");
                while(rs.next())
                    data.add(rs.getString("id_kontak"));
            } catch (SQLException ex) {
                Logger.getLogger(addPesertaEvent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            for(int i=0;i<jTable1.getRowCount();i++)
                if((boolean)jTable1.getValueAt(i, jTable1.getColumnCount()-1))
                    data.add((String)jTable1.getValueAt(i, 0));
        }
        return data;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("tambahkan dari group"));

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("tambahkan peserta dari group");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("tambahkan dari kontak"));

        jRadioButton2.setText("Tambahkan Peserta dari kontak");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(0, 584, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTable1.setEnabled(false);
        jPanel2.setEnabled(false);
        jComboBox1.setEnabled(true);
        jPanel1.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setEnabled(false);
        jPanel1.setEnabled(false);
        jTable1.setEnabled(true);
        jPanel2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()&&jTable1.getSelectedColumn()!=jTable1.getColumnCount()-1){
            if((boolean)jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getColumnCount()-1))
                jTable1.setValueAt(false,jTable1.getSelectedRow(), jTable1.getColumnCount()-1);
            else
                jTable1.setValueAt(true,jTable1.getSelectedRow(), jTable1.getColumnCount()-1);
        }
        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
