/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eventremainder;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Komando
 */
public class paneImage extends javax.swing.JPanel {

    /**
     * Creates new form paneImage
     */
    BufferedImage img = null;
    public paneImage() {
        initComponents();
    }
    public void setBacground(BufferedImage a){
            img = a;
            revalidate();
            repaint();
    }
    public void paintComponent(Graphics g) {
        if(img!=null)
            g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);
        else
            g.fillRect(0, 0, this.getWidth(), this.getHeight());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
