/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventremainder;

import javax.swing.BorderFactory;
import javax.swing.JProgressBar;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Saputro
 */
public class progressSms extends javax.swing.JPanel {

    /**
     * Creates new form progressSms
     */
    int id=0;
    mainFrame mainframe;
    public progressSms(mainFrame mainframe) {
        initComponents();
        this.mainframe = mainframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar(0, 1000);

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setId(int i){
        id = i;
    }
    public void setProgressName(String title){
        BorderFactory.createTitledBorder( ((TitledBorder)this.getBorder()), title ) ;
    }
    public void setValueProgressBar (int val){
        jProgressBar1.setValue(val);
    }
    public int getMaxValueProgressBar (){
        return jProgressBar1.getMaximum();
    }
    public void addToList(){
        mainframe.addProgress(this);
    }
    public void removeFromList(){
        mainframe.removeProgress(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
