/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eventremainder;
import javax.imageio.ImageIO;
import toModem.portSearch;
/**
 *
 * @author Komando
 */
public class start extends javax.swing.JPanel {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(portSearch.prosesCariPort()));
        jComboBox1.setSelectedIndex(jComboBox1.getItemCount()-1);
    }
    public String getPort(){
        if(portSearch.prosesCariPort().size()==1){
            return (String) portSearch.prosesCariPort().get(0);
        }
        return (String)jComboBox1.getSelectedItem();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneImage1 = new eventremainder.paneImage();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        try{
            paneImage1.setBacground(ImageIO.read(getClass().getResourceAsStream("/images/head.PNG"))); // NOI18N
        }catch(Exception e){
            System.out.println(e);}

        javax.swing.GroupLayout paneImage1Layout = new javax.swing.GroupLayout(paneImage1);
        paneImage1.setLayout(paneImage1Layout);
        paneImage1Layout.setHorizontalGroup(
            paneImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        paneImage1Layout.setVerticalGroup(
            paneImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel3.setText("Port Modem ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, 0, 293, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paneImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private eventremainder.paneImage paneImage1;
    // End of variables declaration//GEN-END:variables
}
